# Generated by Django 4.1 on 2022-08-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='手机号码')),
                ('grade', models.CharField(max_length=10, verbose_name='所属年级')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.user', verbose_name='所属号码')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
    ]
