# Generated by Django 3.2.5 on 2022-08-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '市场信息', 'verbose_name_plural': '市场信息'},
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='所属年级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='所属号码'),
        ),
    ]
