# Generated by Django 3.2.5 on 2022-08-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20220818_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(max_length=10, verbose_name='所属年级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
    ]
